# USERS

User.create(first_name: 'Admin', last_name: 'Admin', email: 'admin@foodee.com', password: '1234567890', profile: 'administrator')
User.create(first_name: 'Jhon', last_name: 'Doe', email: 'waiter@foodee.com', password: '1234567890', profile: 'waiter')

# EVENTS

Event.create(title: 'Kitchen Workshops', description: 'Magni reprehenderit sint delectus in ipsa recusandae ducimus.', finalized_date: DateTime.parse('2016-08-15 09:30:00'))
Event.create(title: 'Music Concerts', description: 'Magni reprehenderit sint delectus in ipsa recusandae ducimus.', finalized_date: DateTime.parse('2016-08-11 21:30:00'))
Event.create(title: 'Free to Eat Party', description: 'Magni reprehenderit sint delectus in ipsa recusandae ducimus.', finalized_date: DateTime.parse('2016-08-20 20:20:00'))
Event.create(title: 'Pizza Party', description: 'Magni reprehenderit sint delectus in ipsa recusandae ducimus.', finalized_date: DateTime.parse('2016-08-16 18:25:00'))

# DISHES

type_dish = Product::TYPES[:dish]
Product.create(name: 'focaccia bread', description: 'hand made bread baked with extra virgin olive oil, sea salt and rosemary', price: 2.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'garlic bread', description: 'hand made bread baked with garlic and extra virgin olive oil', price: 2.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'bruschetta', description: 'slices of baked bread garnished with cherry tomatoes, extra virgin olive oil, origano & basil', price: 5.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'potato wedges', description: 'oven baked potatoes wedges served with home made mayo', price: 5.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'stuzzichini mix', description: 'includes 3 bowls: olives; tarallini – special baked bread from salento; dry fruit: almonds, walnuts, pistachio, hazelnuts, cashew', price: 5.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'soup of the day', description: 'vegetable soup served with focaccia bread', price: 6.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'bread basket', description: 'hand made basket made out of bread (which you can eat as well) containing a garlic bread, focaccia bread and bread slices', price: 7.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'scrambled tofu and vacon', description: 'scrambled eggy tofu salad with onions and chives, topped with crispy seitan served with bread slices', price: 7.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'carpaccio seitan', description: 'carpaccio served with rocket, beetroot sauce and grated cheese (parmesan style cheese)', price: 7.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'cheesy balls', description: 'home made cashew goat cheese style served on veggie spreads and bread slices', price: 8.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'raw bytes', description: 'raw sundried tomatoes and flax seeds cracker served with cashew spreadable cheese, olives, cherry tomatoes and rocket', price: 9.95, category: 'Starters', product_type: type_dish)
Product.create(name: 'platter bread', description: 'basket served with slices of various cold cuts (soya ham, spicy seitan salami, soya sausage, seitan carpaccio,', price: 15.95, category: 'Starters', product_type: type_dish)

Product.create(name: 'marinara', description: 'back to the basics tomato sauce, garlic & origano', price: 5.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'margherita', description: 'old skool classic  tomato sauce, mozzarella style cheese*, origano & basil', price: 7.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'farmer', description: 'tomato sauce, beetroot cream, mozzarella style cheese* & mixed seeds: sunflower, pumpkin, sesame, flax, poppy, hemp', price: 9.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'hot', description: 'tomato sauce, mozzarella style cheese*, spicy seitan salami, chilli and olives', price: 11.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'fresh', description: 'tomato sauce, mozzarella style cheese*, smoked tofu, capers, olives & rocket', price: 11.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'exotic', description: 'tomato sauce, mozzarella style cheese*, mushrooms and dry fruit: almonds, walnuts, pistachio, hazelnuts', price: 12.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'wild', description: 'broccoli cream, mozzarella style cheese*, cherry tomaotes, portobellos mushrooms and soya sausage', price: 13.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'nature', description: 'tomato sauce, mozzarella style cheese*, aubergines, courgettes, peppers, artichokes, portobellos mushrooms and olives', price: 13.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: '4 stagioni', description: 'tomato sauce, mozzarella style cheese*, portobello mushrooms, soy ham, soy sausage, artichokes & olives', price: 13.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'heaven', description: 'tomato sauce, mozzarella style cheese*, soya ham, spicy seitan salami, soya sausage & olives', price: 13.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'cheesy', description: 'mozzarella style cheese* and a mix of cheese: mozzarisella, red cheddar & blue cheese style, in-house made cashew cheese and walnuts', price: 15.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'experience ltj', description: 'tomato sauce, mozzarella style cheese*, asparagus, cherry tomatoes, carpaccio seitan salami, rocket and grated parmesan style cheese', price: 15.95, category: 'Pizza or Calzone', product_type: type_dish)
Product.create(name: 'the king starter', description: 'tomato sauce, mozzarella style cheese*, a mix of in-house made cashew cheese, seitan carpaccio and spicy seitan salami', price: 15.95, category: 'Pizza or Calzone', product_type: type_dish)

Product.create(name: 'aglio, olio e peperoncino', description: 'freshly made with garlic, fresh and crushed chilli & extra virgin olive oil', price: 8.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'pomodoro or arrabbiata', description: 'freshly made with tomato sauce & basil or freshly made with tomato sauce, crushed and fresh chilli', price: 9.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'pesto', description: 'freshly made with green-basil pesto sauce', price: 10.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'polpette di verdure', description: 'freshly made with veggies balls and tomato sauce', price: 11.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'ragù soya bolognese', description: 'freshly made with bolognese soya ragù sauce (contains soya, onions, carrots & celery)', price: 12.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'riccio capriccio', description: 'freshly made with creamy peppers sauce and a touch of seaweed', price: 12.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'boscaiola', description: 'freshly made with creamy broccoli and soya sausage (optional: for a better experience have it spicy)', price: 12.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'amatriciana', description: 'london style  freshly made with tomato sauce, nutritional yeast topped with crispy seitan chunks', price: 12.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'carbonara – london style', description: 'freshly made with soya cream and tofu, topped with crispy seitan chunks', price: 13.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'mare e monti', description: 'freshly made seaweed, cashews, pistachios, cherry tomatoes, olives and capers', price: 13.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'tricolore', description: 'freshly made with green-basil pesto sauce, beetroot cream, walnuts sauce', price: 13.95, category: 'Pasta', product_type: type_dish)
Product.create(name: 'salento', description: 'freshly made with tomato sauce, aubergines, walnuts and cashew bufala mozzarella style', price: 13.95, category: 'Pasta', product_type: type_dish)

Product.create(name: 'sweeataly freshly', description: 'made greens with cherry tomatoes, capers, olives, sundried tomatoes and bread', price: 7.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'fedslaw freshly', description: 'made greens with red cabbage, carrots, apple, olives, mayo and bread', price: 8.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'greenland freshly', description: 'made greens with red cabbage, smoked tofu, cherry tomatoes, beetroot sauce and bread', price: 10.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'fed fields', description: 'freshly made greens with carrots, cherry tomatoes, olives, seitan carpaccio, cheese balls and bread', price: 11.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'slowado', description: 'freshly made greens with carrots, avocado, smoked tofu, mixed seeds and bread', price: 11.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'lasagne', description: 'homemade lasagne baked with soya ragú, served with fresh salad, hummus and crunchy bread', price: 12.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'parmigiana', description: 'aubergines sliced baked with soya ragú, served with fresh salad and veggies dices and crunchy bread', price: 12.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'ballox', description: 'veggie balls, cheesy balls and grain of the day served with broccoli sauce, fresh salad and bread', price: 12.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'grains party', description: 'grain salad mixed with home made cashew cheese and shredded courgettes, crunchy veggies and salad', price: 12.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'scrambled tofu', description: 'scrambled tofu served with greens and potato wedges and bread', price: 12.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'carpaccio seitan', description: 'carpaccio served with rocket, beetroot sauce, grain salad and veggies dices', price: 13.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'spiedini', description: 'soya chunks skewers served with potatoes wedges and freshly made salad', price: 13.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'burgerland', description: 'beetroot, tofu & sweet potatoes, soya burgers served with potato wedges, mayo and fresh salad', price: 14.95, category: 'Salads & Mains', product_type: type_dish)
Product.create(name: 'raw courgette spaghetti', description: 'courgette spaghetti with cherry tomatoes, capers, olives, onion, served with salad and bytes with raw spread', price: 14.95, category: 'Salads & Mains', product_type: type_dish)

Product.create(name: "Strawberry & cream sandwich sponge", description: "This classic cake is, of course, named after Queen Victoria, the only monarch to reign longer than the current Queen. It’s relatively easy to make but does have a few quirks: you need to get as much air into it as possible, and be mindful of its sensitivity to variations in heat. Know your oven well and invest in an oven thermometer!", price: 6.50, category: 'Dessert', product_type: type_dish)
Product.create(name: "Chocolate mousse with prunes", description: "Any leftover prune mixture will keep in an airtight container for up to a month – try it with rice pudding!", price: 6.50, category: 'Dessert', product_type: type_dish)
Product.create(name: "Chocolate truffle chestnut torte with honeycomb", description: "A decadent torte so rich you’ll only need a little slice! This recipe makes more honeycomb than you’ll need, but leftovers will store for a week in an airtight container.", price: 6.00, category: 'Dessert', product_type: type_dish)
Product.create(name: "Lemon sorbet", description: "Try to find Sicilian or Amalfi lemons for this – they may be more expensive than regular lemons, but their sharp flavour is perfect for this palate-cleanser. You can also add a shot of vodka or grappa – for adults only!", price: 4.50, category: 'Dessert', product_type: type_dish)
Product.create(name: "Rhubarb sorbet with pistachio brittle", description: "Sweet yet tart rhubarb sorbet with salty, crunchy brittle – flavours and textures that go mad in your mouth.", price: 4.75, category: 'Dessert', product_type: type_dish)
Product.create(name: "Roasted banana & cinnamon ice cream", description: "Somewhere between frozen yoghurt and ice cream, this is easy to make and oh-so hard to resist.", price: 5.50, category: 'Dessert', product_type: type_dish)


# DRINKS

type_drink = Product::TYPES[:drink]
Product.create(name: 'Casanova Strawberry Bellini', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 10.00 , category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Casanova Peach Bellini', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 10.00   , category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Views Kir Royal', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 10.00 , category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Honey Casanova', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Lady Casanova', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Passion Margarita with a view', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Strawberry Magarita with a view', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Strudel Mojito', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Chelsea Cosmo', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'True Romance', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Pina Colada', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Long Island tea', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Strawberry Daiquiri', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Old Fashion', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Caiprinha', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Bloody Mary', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Pornstar Martini', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Cuba Libre', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Classic Martini', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)
Product.create(name: 'Negroni', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 12.00, category: 'Cocktails', product_type: type_drink)

Product.create(name: 'Casanova Henriette Cuvee', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 35.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Casanova Prosecco Doc Millesimato', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 40.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Casanova Prosecco Rose Cuvee', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 40.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Casanova Rose white Cuvee white Edition', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 45.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Veuve Clicquot Yellow Label', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 78.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Moet et Chandon Rose', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 85.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Laurrent - Perrier Rose', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 102.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Dom Perignon', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 240.00, category: 'Prosecco', product_type: type_drink)
Product.create(name: 'Louis Roederer Cristal', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 360.00, category: 'Prosecco', product_type: type_drink)

Product.create(name: 'Via Alta Sauvignon Blanc', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 29, category: 'White Wine'  , product_type: type_drink)
Product.create(name: 'Sereno Pinot Grigio', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 34, category: 'White Wine' , product_type: type_drink)
Product.create(name: 'Pouilly Fuisse, Domaine Trouillet', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 54, category: 'White Wine', product_type: type_drink)

Product.create(name: 'La Grupa Malbec', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 34, category: 'Red Wine', product_type: type_drink)
Product.create(name: 'Charles smith, “The Velvet Devil” Merlot', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 44, category: 'Red Wine', product_type: type_drink)
Product.create(name: 'Brunello di Montacini', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 90, category: 'Red Wine', product_type: type_drink)

Product.create(name: 'Peroni Nastro Azzuro', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 4.5, category: 'Beers', product_type: type_drink)
Product.create(name: 'Corona', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 5, category: 'Beers', product_type: type_drink)

Product.create(name: 'Bacardi superior rum 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 6.5, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Malibu 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 6.5, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Ciroc Vodka 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 8, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Patron silver 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 14, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Patron Cafe 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 9.5, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Martel Cognac 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 8, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'J walker Black whiskey 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 7, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Baileys 50ml', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 6.5, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Greygoose vodka', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 150, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Circo Vodka', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 170, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Jack Daniels', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 180, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Remy Martin', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 190, category: 'Spirits/Liquors', product_type: type_drink)
Product.create(name: 'Courvosier', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus et lacus at suscipit. Vestibulum.', price: 200, category: 'Spirits/Liquors', product_type: type_drink)
